dist: xenial
language: node_js
node_js: "10"
cache: npm

env:
  - DATABASE_URL="psql://postgres:@localhost/clerk_test"

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database clerk_test;' -U postgres
  - psql -U postgres -d clerk_test < src/db/schema.sql
