name: Run Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10, 12, latest]

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clerk_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Create database
      uses: docker://postgres:11
      with:
        args: -c 'create database clerk_test;' -U postgres
    - name: Set up schema
      uses: docker://postgres:11
      with:
        args: -U postgres -d clerk_test < src/db/schema.sql
    - name: Run tests
      env:
        DATABASE_URL: psql://postgres:postgres@postgres:${{ job.services.postgres.ports[5432] }}/clerk_test
        CI: true
      run: npm test
