name: Run Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10, 12]

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clerk_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Set up database
      run: psql < src/db/schema.sql
      env:
        PGPASSWORD: postgres
        PGUSER: postgres
        PGHOST: localhost
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGDATABASE: clerk_test
    - name: Run tests
      env:
        DATABASE_URL: psql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/clerk_test
        CI: true
        FORCE_COLOR: true
      run: npm test
